# Generated by Django 6.0.2 on 2026-04-05 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comptition_Request_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=20)),
                ('publish_status', models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish')], default='unpublish', max_length=20)),
                ('party_nik_name', models.CharField(max_length=5)),
                ('party_FullName', models.CharField(max_length=55)),
                ('party_chairman_name', models.CharField(max_length=20)),
                ('want_lead', models.CharField(choices=[('Afar Region', 'Afar Region'), ('Amhara Region', 'Amhara Region'), ('Benishangul-Gumuz Region', 'Benishangul-Gumuz Region'), ('Gambela Region', 'Gambela Region'), ('Harari Region', 'Harari Region'), ('Oromia Region', 'Oromia Region'), ('Somali Region', 'Somali Region'), ('Sidama Region', 'Sidama Region'), ('South West Ethiopia Peoples Region', 'South West Ethiopia Peoples Region'), ('Southern Ethiopia Regional State', 'Southern Ethiopia Regional State'), ('Central Ethiopia Regional State', 'Central Ethiopia Regional State'), ('Tigray Region', 'Tigray Region')], max_length=55)),
                ('party_discription', models.TextField()),
                ('party_info_PDF', models.FileField(upload_to='Parties/PDF/')),
                ('party_logo', models.ImageField(upload_to='Parties_logo/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Approvement_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='public.comptition_request_model')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
