# Generated by Django 6.0.2 on 2026-03-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comptition_Request_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_nik_name', models.CharField(max_length=5)),
                ('party_FullName', models.CharField(max_length=55)),
                ('party_chairman_name', models.CharField(max_length=20)),
                ('want_lead', models.CharField(choices=[('Afar Region', 'Afar Region'), ('Amhara Region', 'Amhara Region'), ('Benishangul-Gumuz Region', 'Benishangul-Gumuz Region'), ('Gambela Region', 'Gambela Region'), ('Harari Region', 'Harari Region'), ('Oromia Region', 'Oromia Region'), ('Somali Region', 'Somali Region'), ('Sidama Region', 'Sidama Region'), ('South West Ethiopia Peoples Region', 'South West Ethiopia Peoples Region'), ('Southern Ethiopia Regional State', 'Southern Ethiopia Regional State'), ('Central Ethiopia Regional State', 'Central Ethiopia Regional State'), ('Tigray Region', 'Tigray Region')])),
                ('party_discription', models.TextField()),
                ('party_info_PDF', models.FileField(upload_to='Parties/PDF/')),
            ],
        ),
    ]
