# Generated by Django 6.0.2 on 2026-03-23 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptition_request_model',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Approvement_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_uesd', models.BooleanField(default=False)),
                ('request_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.comptition_request_model')),
            ],
        ),
    ]
