# Generated by Django 6.0.2 on 2026-03-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptition_request_model',
            name='publish_status',
            field=models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish')], default='unpublish', max_length=20),
        ),
    ]
