# Generated by Django 6.0.2 on 2026-03-23 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_comptition_request_model_status_approvement_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvement_token',
            name='request_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='public.comptition_request_model'),
        ),
    ]
