# Generated by Django 6.0.2 on 2026-04-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
