# Generated by Django 6.0.2 on 2026-03-23 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_approvement_token_request_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvement_token',
            old_name='is_uesd',
            new_name='is_used',
        ),
        migrations.RemoveField(
            model_name='approvement_token',
            name='request_status',
        ),
        migrations.AddField(
            model_name='approvement_token',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='public.comptition_request_model'),
        ),
    ]
