# Generated by Django 6.0.2 on 2026-04-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_vote_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='slug',
        ),
    ]
